### PR TITLE
remove babel-loader and make node process sourcemap with server code

### PR DESCRIPTION
**Pull request by sterproton**
I have fork your newest repo.
I have check it, you can see it

### CODE REVIEW

**Comment by sterproton** [comment]
- import graphql
- upgrade babel
- parcel dev/prod
- jest error

have any problem? just leave a comment, and i will process it

**Comment by sterproton** [comment]
sorry about my previous comment, you know, it is the first time i do a freelancer work, so i have some worry, sorry

**Comment by janat08** [comment]
prove that it works

**Comment by sterproton** [comment]
ok, i will make screen shot for you

**Comment by sterproton** [comment]
with sourcemap
image

without sourcemap

image

**Comment by janat08** [comment]
How does it still reference dist? What about graphql

**Comment by sterproton** [comment]
graphql import does work as what i have config, i have make a example, you can merge it or clone repo  to check it

**Comment by sterproton** [comment]
the example like this
clien side:
image

three graphql file:
hellos.graphql
```
fragment hellos on Query{
  hello
  hello2
  hello3
}
```
worlds.graphql
```
fragment worlds on Query{
  world
  world2
  world3
}
```
index.graphql
```
#import "./hellos.graphql"
#import "./worlds.graphql"

query test{
  ...hellos
  ...worlds
}
```

client index.js
```js
import ApolloClient from 'apollo-boost';
import query from './index.graphql';
const testClient = new ApolloClient({
	uri: 'http://localhost:5000/graphql'
});

testClient.query({
	query,
}).then((data) => {
	console.log('graphql import does work, check the imported graphql file');
	console.log('test graphql import, fetched data', data);
});

```

server side
image

testgraphql.js

```js
const express = require('express');
const { ApolloServer, gql } = require('apollo-server-express');

// Construct a schema, using GraphQL schema language
const typeDefs = gql`
  type Query {
    hello: String
    hello2: String
    hello3: String
    world: String
    world1:String
    world2: String
    world3: String
  }

`;

// Provide resolver functions for your schema fields
const resolvers = {
	Query: {
		hello: () => 'hello',
		hello2: () => 'hello2',
		hello3: () => 'hello3',
		world: () => 'world',
		world1: () => 'world1',
		world2: () => 'world2',
		world3: () => 'world3',
	},
};

const server = new ApolloServer({ typeDefs, resolvers });

const app = express();
server.applyMiddleware({ app });

app.listen({ port: 5000 });

```

**Comment by sterproton** [comment]
and the result
image

**Comment by janat08** [comment]
copy over the example to this repo. There're still 2 graphql import babel plugins in my repo.

**Comment by janat08** [comment]
there're two graphql import babel plugins installed, babel loader supposedly is responsible for clearing graphql cache

**Comment by sterproton** [comment]
it is weird, but babel-loader is a webpack plugin for loading babel config, and it is not for clear graphql cache. i will check it

**Comment by sterproton** [comment]
i will try to install the babel-loader for babel 7. and see what happen

**Comment by sterproton** [comment]
i know why this happen😂 because the babel plugin `babel-plugin-import-graphql`'s cache logic only consider the webpack's plugin(babel-loader)
see this
image

so the developer of import graphql plugin only consider webpack's cache logic and this is why he suggest us clear the cache use this way😂

in the import graphql plugin document
image

**Comment by sterproton** [comment]
so there are three ways(maybe only two way) can solve the problem:
1. raise a issue in parcel-bundler, let them fix this graphql file cache problem or
2. raise a issue in babel-plugin-graphql-import, let the developer suppport parcel's cache mechanism

3. make a hook to detect graphql file change and re-start parcel.......  I think this is impossible to do it

**Comment by sterproton** [comment]
I have raised a issue in parcel's repo
https://github.com/parcel-bundler/parcel/issues/2370

**Comment by janat08** [comment]
screenshot 6

**Comment by janat08** [comment]
deleting the .cache directory in root helped.

**Comment by sterproton** [comment]
Oh, I see, the .cache folder is for parcel's cache, so it work

**Comment by sterproton** [comment]
so what is next i need to do
- import graphql
- upgrade babel
- parcel dev/prod
- jest error
is there any problem?

**Comment by sterproton** [comment]
I can write a hook to delete the .cache

**Comment by sterproton** [comment]
so is there any problem?

**Comment by sterproton** [comment]
oh, thank you very much, i have recieve the milestone

**Pull request merged**
