### PR TITLE
ok

### PR DESCRIPTION
**Pull request by sterproton**
have make yarn dev yarn prod use parcel run server

### CODE REVIEW

**Comment by sterproton** [comment]
and i have requested release milestone in freelancer. check it

**Comment by janat08** [comment]
I would've preferred if you stopped opening separate pull requests as I don't have to review changes again.

**Comment by sterproton** [comment]
The commit record didn't change

**Comment by janat08** [comment]
Lol I eslinted package.json on the latest branch. Make fixes from typescript examples if they have to be made.

**Comment by janat08** [comment]
PS updated master

**Comment by janat08** [comment]
I haven't checked this out yet

**Comment by janat08** [comment]
warning " > babel-loader@7.1.5" has incorrect peer dependency "babel-core@6".

**Comment by janat08** [comment]
lol there're no sourcemaps for server (I resolved conflicts poorly it seems).

**Comment by janat08** [comment]
PS I know what this is about.

**Comment by sterproton** [comment]
1. babel-loader, it is you installed it , and seems like don't make any use and don't make any sens, just remove it 
2.  about source-map, it is enable by default, i didn't config close source-map

**Comment by sterproton** [comment]
you forget to release the milestone on freelancer 🙂

**Comment by janat08** [comment]
Actually I don't. There're no sourcemap for when you do referenceError or something, besides this after the merge:
``
  1 | (function (global, factory) {
> 2 |     typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('react-dom/server'), require('apollo-client'), require('prop-types'), require('react')) :    |                                                                                            ^
  3 |     typeof define === 'function' && define.amd ? define(['exports', 'react-dom/server', 'apollo-client', 'prop-types', 'react'], factory) :
  4 |     (factory((global['react-apollo'] = {}),global.server,global.apolloClient,global.PropTypes,global.React));
  5 | }(this, (function (exports,server,apolloClient,PropTypes,React) { 'use strict';
``

**Comment by janat08** [comment]
You could try running it directly without parcel and see if this crap is any more intelligible at which point I'll have you configure parcel correctly.

**Comment by sterproton** [comment]
node don't support source map directly. You can Google it.

**Comment by sterproton** [comment]
Although I have helped you solve this problem, I want you know this is not part of my job.
parcel does run successfully and generate sourcemap. 
node don't support sourcemap, this is not parcel's fault. and I have give you the solution.

please clearly tell me. have you checked my work? what part of my work don't pass you check and please list it with the reason.

**Comment by sterproton** [comment]
i have check it. the parcel build error, so parcel don't generate sourcemap
it is because the dependency react-apollo
`C:\Users\chois\Desktop\makpal6\makpal\node_modules\react-apollo\react-apollo.browser.umd.js:2:92: Cannot resolve dependency 'react-dom/server'`

**Comment by sterproton** [comment]
i have solve this
react-apollo need dependency 'react-dom'
image

**Comment by sterproton** [comment]
by the way, this is not parcel's fault nor part of my work, though i have solve this problem.
What I want you know is, I was ask to config parcel for dev, prod env, and **it is done**, now parcel run in the right way. 

what is more?
**please clearly tell me your check on my work** and the milestone

**Comment by janat08** [comment]
Make a reference error on server on your branch and then on old master. That would be called a regression.

**Comment by janat08** [comment]
regarding the babel loader, you actually make use of it, I believe it's responsible for caching graphql, resolve the peer dependencies.

**Comment by sterproton** [comment]
ok.
so now you want to solve the sourcemap problem right?
> please clearly tell me your check on my work and the milestone. i don't want to waste time
what about the check, you didn't answer me. what part of my work pass your check. what part didn't and why?

or there is just only a sourcemap problem, other part of my work have passed the check?

**Comment by janat08** [comment]
It doesn't load either. Why won't you do me another favor.

**Comment by sterproton** [comment]
ok, i will do it

**Comment by sterproton** [comment]
wait a minute

**Comment by sterproton** [comment]
and please tell me about the check ok?

**Comment by sterproton** [comment]
you didn't give me a clearly response about my work and the milestone.

**Comment by sterproton** [comment]
I will do you another favor. but you know, you haven't release the milestone. you didn't pay me for the previous work???? so??

**Comment by sterproton** [comment]
what wrong with you?

**Comment by sterproton** [comment]
Import graphql is work, I config it like the documents

babel-loader is for webpack, remove it. I didn't installed it

parcel work great right? where is the crap error,  your server code don't handle map file,and it is your problem, but I still help you right? and node sourcemap, I can do you favor. So what is wrong that I say parcel work great??

**Comment by sterproton** [comment]
Jest error, I solve it and make screenshot for you right?

**Comment by sterproton** [comment]
So, this is why I ask you to clearly tell me my work.

**Comment by sterproton** [comment]
you can import graphql file and log it, you will know it is successfully. or you will get a raw string

**Comment by sterproton** [comment]
So many times i said, check my work and tell me what is wrong

**Comment by sterproton** [comment]
so now do you agree me? Or disagree what part.  I have said good communication don't waste time

**Comment by janat08** [comment]
Telling you the fifth time to fix stack traces, and third time to fix peer conflicts. I will no longer discuss condition in which you return me my repo nor iterate objectives or help you by resolving pull request conflicts or indicating how your work is not up to par after having assumed burden of assessing it.

**Comment by sterproton** [comment]
see, this is why we argue, you thought fix stack trace is part of my work, and i said it is not. and babel-loader peer conflicts. this loader is for webpack😜. and it is you installed it. if you don't believe me just look this old commit 
`https://github.com/janat08/makpal/blob/4a87cf38ac935d760a023815426568bf2e828189/package.json`
and I have said just remove it, and you don't believe me. what ever, this package just meaningless

and seems like you don't want to discuss this?

**Pull request merged**
