### PR TITLE
implement graphql file import

### PR DESCRIPTION
**Pull request by sterproton**
add some useless log statement..... you can remove it when my task is done

### CODE REVIEW

**Comment by sterproton** [comment]
not my problem, your previous code also can't pass the check😂

**Comment by janat08** [comment]
will importing something like user work that will import userProfile fragment with the .graphql file?

**Comment by janat08** [comment]
I was hoping that moving server to parcel would stop these errors that have to do with typescript compiler.

**Comment by sterproton** [comment]
yes, it work! just like this
snipaste_2018-12-01_17-03-14
snipaste_2018-12-01_17-00-56

**Comment by janat08** [comment]
```
#import "./Profile.graphql"

fragment UserInfo on User {
 ...
}
```
This is from User.graphql, note the import. The idea is that I don't have to run gql under any circumstance.

**Comment by janat08** [comment]
When talking about typescript errors on server side I mean this is what keeps semaphoreci from building.

**Comment by sterproton** [comment]
like this?
snipaste_2018-12-01_19-52-20
snipaste_2018-12-01_19-51-19

**Comment by janat08** [comment]
I'll check it out.

**Pull request closed without merging**
